baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
        definitionList = true
        footnote = true
        linkify = true
        strikethrough = true
        table = true
        taskList = true


